name: Build WebGL and Deploy

on:
  push:
    branches: [ master ]
    paths:
      - "OvergodIdle/**"
      - ".github/workflows/build-webgl.yml"

permissions:
  contents: write

env:
  PROJECT_PATH: OvergodIdle
  TARGET_PLATFORM: WebGL
  UNITY_VERSION: 6000.1.15f1
  CACHE_EDITOR: "true"

jobs:
  buildWebGL:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: >
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}-
            ${{
              hashFiles(
                format('{0}/Packages/manifest.json', env.PROJECT_PATH),
                format('{0}/ProjectSettings/ProjectVersion.txt', env.PROJECT_PATH)
              )
            }}
          restore-keys: |
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}-
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-
            Library-${{ runner.os }}-

      - name: Build (Unity Builder)
        uses: game-ci/unity-builder@v4
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: ${{ env.TARGET_PLATFORM }}
          unityVersion: ${{ env.UNITY_VERSION }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}

      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: build/${{ env.TARGET_PLATFORM }}

  deployToPages:
    needs: buildWebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Unity WebGL artifact
        uses: actions/download-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL

      - name: Prepare Unity files into Vite public/
        shell: bash
        run: |
          set -e
          VITE_ROOT=OvergodIdle/Assets/WebGLTemplates/OvergodIdle
          mkdir -p "$VITE_ROOT/public"
          if [ -d build/WebGL/Build ]; then
            rm -rf "$VITE_ROOT/public/Build"
            cp -R build/WebGL/Build "$VITE_ROOT/public/"
          fi
          if [ -d build/WebGL/StreamingAssets ]; then
            rm -rf "$VITE_ROOT/public/StreamingAssets"
            cp -R build/WebGL/StreamingAssets "$VITE_ROOT/public/"
          fi
          if [ -d build/WebGL/TemplateData ]; then
            rm -rf "$VITE_ROOT/public/TemplateData"
            cp -R build/WebGL/TemplateData "$VITE_ROOT/public/"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: OvergodIdle/Assets/WebGLTemplates/OvergodIdle/package.json

      - uses: actions/cache@v4
        with:
          path: OvergodIdle/Assets/_ThirdParty/game-client-sdk/node_modules
          key: sdk-npm-${{ hashFiles('OvergodIdle/Assets/_ThirdParty/game-client-sdk/package-lock.json') }}

      - name: Install SDK deps and build
        working-directory: OvergodIdle/Assets/_ThirdParty/game-client-sdk
        run: |
          npm ci
          npm run build

      - name: Install dependencies (Vite template)
        working-directory: OvergodIdle/Assets/WebGLTemplates/OvergodIdle
        run: npm ci --ignore-scripts

      - name: Build Vite template
        working-directory: OvergodIdle/Assets/WebGLTemplates/OvergodIdle
        run: npm run build

      - name: SPA fallback (copy index.html to 404.html)
        working-directory: OvergodIdle/Assets/WebGLTemplates/OvergodIdle
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: OvergodIdle/Assets/WebGLTemplates/OvergodIdle/dist
