name: Build WebGL and Deploy

on:
  push:
    branches: [ master ]

env:
  PROJECT_PATH: OvergodIdle
  TARGET_PLATFORM: WebGL
  UNITY_VERSION: 6000.1.15f1

jobs:
  buildWebGL:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache Library with keys that change when:
      # - OS changes
      # - Unity version changes
      # - Target platform changes
      # - Packages or Unity project version change
      - uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: >
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}-
            ${{
              hashFiles(
                format('{0}/Packages/manifest.json', env.PROJECT_PATH),
                format('{0}/ProjectSettings/ProjectVersion.txt', env.PROJECT_PATH)
              )
            }}
          restore-keys: |
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}-
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-
            Library-${{ runner.os }}-

      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ env.TARGET_PLATFORM }}
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: ${{ env.PROJECT_PATH }}/build/${{ env.TARGET_PLATFORM }}

  deployToPages:
    needs: buildWebGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL
