name: Build WebGL and Deploy

on:
  push:
    branches: [ master ]
    paths:
      - "OvergodIdle/**"
      - ".github/workflows/build-webgl.yml"

env:
  PROJECT_PATH: OvergodIdle
  TARGET_PLATFORM: WebGL
  UNITY_VERSION: 6000.1.15f1
  CACHE_EDITOR: "true"

jobs:
  buildWebGL:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Editor
        if: env.CACHE_EDITOR == 'true'
        uses: actions/cache@v4
        with:
          # Include common Linux locations used by GameCI/Unity for downloads & installs
          path: |
            ~/.local/share/unity3d
            ~/.cache/unity3d
            ~/.cache/unity
            $HOME/.cache/unity
          key: UnityEditor-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}
          restore-keys: |
            UnityEditor-${{ runner.os }}-${{ env.UNITY_VERSION }}-
            UnityEditor-${{ runner.os }}-

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: >
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}-
            ${{
              hashFiles(
                format('{0}/Packages/manifest.json', env.PROJECT_PATH),
                format('{0}/ProjectSettings/ProjectVersion.txt', env.PROJECT_PATH)
              )
            }}
          restore-keys: |
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ env.TARGET_PLATFORM }}-
            Library-${{ runner.os }}-${{ env.UNITY_VERSION }}-
            Library-${{ runner.os }}-

      - name: Build (Unity Builder)
        uses: game-ci/unity-builder@v4
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: ${{ env.TARGET_PLATFORM }}
          unityVersion: ${{ env.UNITY_VERSION }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}

      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: ${{ env.PROJECT_PATH }}/build/${{ env.TARGET_PLATFORM }}

  deployToPages:
    needs: buildWebGL
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL
